### ISSUE TITLE
My Buwizz v1 device is not able to keep constant channel output for longer period

### ISSUE THREAD

**Issue by vicocz** [imurvai/brickcontroller2#78]
I've got Buwizz v1 device recently and it has following strange behavior: If there is constant motor output (e.g. via simple toggle or just during testing of channel output), the output is stopped after circa 3 seconds unless a channel change triggers another output write. The original Buwizz v1 app works fine.
Hard to decide whether it's bug in BC2 or just a kind of malfunction of my device. I've Brick Controller 2 v3.0 running on Android.
Could someone, who has V1 device, confirm it please?

**Comment by DenoG1997** [comment]
@vicocz @imurvai  how can i get access to TestFlight because I want to test the servo function for the Buwizz 3.0

**Comment by imurvai** [comment]
ah, sorry, I haven't had time yet to upload the recent changes to testflight

**Comment by DenoG1997** [comment]
No problem but I don’t even know how to install it on my iPhone even if you upload it

**Comment by DenoG1997** [comment]
Can you tell me what Ive to do?

**Comment by imurvai** [comment]
As far as I know once I add you to my testfligh then it will let you know when a new app is ready to be tested. So could you send me your email address?

**Comment by DenoG1997** [comment]
Yes great ! caan97@hotmail.de

**Comment by imurvai** [comment]
Thanks, I added you to the testers.

**Comment by DenoG1997** [comment]
![image](https://user-images.githubusercontent.com/74460597/151545637-34ef2208-fbcf-4d3a-839c-b67c0ca1e5d2.jpeg)

this is my recent fastest and best car with buwizz 3.0

**Comment by DenoG1997** [comment]
but it is so fast that it very hard go control ist with the touchpad when you full buwizz support it than i can control it mich vetter with an controller

**Comment by DenoG1997** [comment]
im studying now and next semester i will learn C an C++ i will can help you to programm
