### ISSUE TITLE
Q: Migration from Xamarin 5 to .NET MAUI

### ISSUE THREAD

**Issue by vicocz** [imurvai/brickcontroller2#85]
Hi,
do you have any plans to migrate from Xamarin.Forms 5 to newly developed .NET MAUI? Currently still in preview, but IMHO this is the future UI for multiplatform apps.
E.g. migration guide: https://github.com/dotnet/maui/wiki/Migrating-from-Xamarin.Forms-(Preview)

**Comment by imurvai** [comment]
Hi, yes  definitely. I lokked into it a bit but didn't eant to start thr migration until it has been released

**Comment by vicocz** [comment]
It have been released, 👀 
https://github.com/dotnet/maui/releases/tag/6.0.312

**Comment by imurvai** [comment]
Wow, cool. Thanks for letting me know :)

**Comment by vicocz** [comment]
Hi, @imurvai, I've started porting to .NET 7 MAUI in my fork, seems I've reach basic factionality of Android app.
Is this something you would be interested to have it merged here? If so, I can create DRAFT to share the state of migration.

**Comment by vicocz** [comment]
DRAFT (to track my progres) is here: https://github.com/imurvai/brickcontroller2/pull/101

**Comment by vicocz** [comment]
@imurvai Support for Xamarin Forms 5.0 is ending soon (on May 1, 2024)
https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin

Do you plan to migrate the project to .NET MAUI?

**Comment by imurvai** [comment]
hey, yes, but unfortunately I can't promise when I'll have time for that.

**Comment by vicocz** [comment]
Resolved by https://github.com/imurvai/brickcontroller2/pull/115
